name: Deploy static content to Pages

on:
  push:
    branches:
      - main  # Deploys when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload site content
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./  # deploy everything in the repository root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        uses: actions/deploy-pages@v4
